# Generated by Django 5.1.1 on 2024-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_museum_matches_logo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextMatches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament', models.CharField(max_length=255, verbose_name='турнир')),
                ('opponent', models.CharField(max_length=255, verbose_name='соперник')),
                ('date', models.DateField(verbose_name='дата матча')),
                ('time', models.TimeField(verbose_name='время начала матча')),
                ('logo1', models.CharField(blank='true', verbose_name='логотип противника')),
                ('description', models.TextField(blank=True, verbose_name='описание матча')),
                ('stadium', models.CharField(max_length=255, verbose_name='стадион')),
                ('link', models.URLField(blank=True, verbose_name='ссылка на матч')),
                ('stats', models.TextField(blank=True, verbose_name='статистика матча')),
            ],
            options={
                'verbose_name': 'не сыгранный матч',
                'verbose_name_plural': 'не сыгранные матчи',
                'db_table': 'main_next_matches',
                'ordering': ['-date', 'id'],
            },
        ),
    ]
